### ISSUE TITLE
September To-Do

### ISSUE THREAD

**Issue by kendalynnm** [COMPASS-DOE/grossMethane#11]
- [x] k -> C
- [x] dilution correction notations
- [x] carry through delta and ppm data

- [x] check code math
- [ ] compare values to Stark pool dilution calcs

- [x] grind and analyze dry soil (total C and N)
- [ ] well CH4 data
- [ ] water-level

- [x] check collar heights
- [x] work-up field data

- [x] 2023 spin up
- [x] assess interests and potential
- [x] assess feasibility
- [x] define scope

- [x] Jilling
